[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "barn-owl"
description = "A fun owl-themed package!"
version = "0.0.1"
authors = [
  { name="Hitaansh Jain", email="hitaansh1912@gmail.com" },
  { name="Aaron Hui", email="aaronhui88@gmail.com" },
  { name="Antonio Jackson", email="aantoniojacksonn@gmail.com" },
  { name="name", email="email@email.com" },
  { name="name", email="email@email.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
keywords = ["python", "package", "build"]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
"Homepage" = "https://github.com/swe-students-spring2026/3-package-barn_owl"
"Repository" = "https://github.com/swe-students-spring2026/3-package-barn_owl.git"
"Bug Tracker" = "https://github.com/swe-students-spring2026/3-package-barn_owl/issues"